export const FETCH_EVENTS_REQUEST = "FETCH_EVENTS_REQUEST";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_FAILED = "FETCH_EVENTS_FAILED";
export const SHOW_SINGLE_EVENT = "SHOW_SINGLE_EVENT";
export const TOGGLE_DRAWER = "TOGGLE_DRAWER";
export const TOGGLE_MENU = "TOGGLE_MENU";
export const SAVE_EVENT_REQUEST = "SAVE_EVENT_REQUEST";
export const SAVE_EVENT_FAILED = "SAVE_EVENT_FAILED";
export const SAVE_EVENT_SUCCESS ="SAVE_EVENT_SUCCESS";


export const REQUEST_FAILED = "REQUEST_FAILED"
export const REQUEST_STARTED = "REQUEST_STARTED"


export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const REQUEST_SIGNUP = "REQUEST_SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";



