export const FETCH_EVENTS_REQUEST = 'FETCH_EVENTS_REQUEST';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const SHOW_SINGLE_EVENT = 'SHOW_SINGLE_EVENT';

// Navigation drawer actions
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const TOGGLE_MENU = 'TOGGLE_MENU';

// Delete dialog actions
export const TOGGLE_DIALOG = 'TOGGLE_DIALOG';


export const SAVE_EVENT_REQUEST = 'SAVE_EVENT_REQUEST';
export const SAVE_EVENT_SUCCESS = 'SAVE_EVENT_SUCCESS';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const RSVP_SUCCESS = 'RSVP_SUCCESS';
export const RSVP_FAILED = 'RSVP_FAILED';
export const RSVP_LOADING = 'RSVP_LOADING';
export const CHANGE_THEME = 'CHANGE_THEME';

export const FETCH_MY_EVENTS_SUCCESS = 'FETCH_MY_EVENTS_SUCCESS';

export const EVENT_FORM_ERROR = 'EVENT_FORM_ERROR';

export const FETCH_REPORTS_SUCCESS = 'FETCH_REPORTS_SUCCESS';

export const CATEGORIES_FETCHED = 'CATEGORIES_FETCHED';

export const REQUEST_FAILED = 'REQUEST_FAILED';
export const REQUEST_STARTED = 'REQUEST_STARTED';

export const FETCH_MAP_SUCCESS = 'FETCH_MAP_SUCCESS';

export const FETCH_GUESTS_SUCCESS = 'FETCH_GUEST_SUCCESS';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const REQUEST_SIGNUP = 'REQUEST_SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const EMAIL_SENT = 'EMAIL_SENT';
export const RESET_TOKEN_ERROR = 'RESET_TOKEN_ERROR';
export const TOKEN_VERIFIED = 'TOKEN_VERIFIED';

