export const FETCH_EVENTS_REQUEST = "FETCH_EVENTS_REQUEST";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const SHOW_SINGLE_EVENT = "SHOW_SINGLE_EVENT";
export const TOGGLE_DRAWER = "TOGGLE_DRAWER";
export const TOGGLE_MENU = "TOGGLE_MENU";
export const SAVE_EVENT_REQUEST = "SAVE_EVENT_REQUEST";
export const SAVE_EVENT_SUCCESS ="SAVE_EVENT_SUCCESS";
export const RSVP_SUCCESS = "RSVP_SUCCESS";
export const RSVP_FAILED = "RSVP_FAILED";
export const RSVP_LOADING = "RSVP_LOADING";


export const EVENT_FORM_ERROR = "EVENT_FORM_ERROR";

export const FETCH_REPORTS_SUCCESS = "FETCH_REPORTS_SUCCESS";


export const REQUEST_FAILED = "REQUEST_FAILED"
export const REQUEST_STARTED = "REQUEST_STARTED"

export const FETCH_MAP_SUCCESS = "FETCH_MAP_SUCCESS"


export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const REQUEST_SIGNUP = "REQUEST_SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";



